# This is a basic workflow to help you get started with Actions

name: deploy website
on:
  # 毎日日本時間の 11時 に GitHub Actions が実行される (cron の時刻は UST)
  # 実行の際に参照されるブランチは上記の default で指定したものが使用される
  schedule:
    - cron:  '*/5 0,1,2 * * *'
  # 一応動確のために手動で GitHub Actions を実行可能にする
  # その際の引数として checkout 時の ref を渡している
  # default 部分はリポジトリに設定されているデフォルトブランチを指定する
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'main'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: deploy
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_3NymfoERFVUfKLnXmcMIOzmKDX2Q/OMZyPmqwQO
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
